language: python
sudo: required
env:
- TOXENV=py27
- TOXENV=py34
install:
- "(!(test -f docker_packages.txt) || (cat docker_packages.txt | xargs sudo apt-get
  install -y))"
- pip install -r requirements_dev.txt
- pip install -r requirements.txt
script: npm run dist
notifications:
  slack:
    secure: Lfbsj3hRTNEQMQxlrNIBJje1XJ5sLLxIXMn/beUB4xPF06+qVeBvNV4N9vURuXGxt2t3dg8NvrYA757RgnbJh34DygVRHrFyIxL9hCxN9M+WW049C1xLHCxbTyadF2tgE7pZHU0p9jaF6Vaffg4+D4TdSNsF30X02z4OEFBBcCaLIVz2d057bg1gSLJ7zKAJ1CkGMNzdhrGXpEATbiQX9GGK2ih1gCIsUTmDSV+Ew4JwxoqpNzpeiBFOc1hxU3z4LERF7XCGq0V4To4KlX8qQWsk9q3f8HUAhRkBKsvlzHIsHUHk/ehwqCyyUVJOHzW1Jj930k3X3tZkrlvGGdA2PH/FusW44fwmDn1v7lt7JieeCHx6oAt5vGgJEnTSFDPY7Uhv57AVCIx0U5pm4VDMyDJYxjUHmJf+wVCl9+FsrTp2pnI/N5SZJ7BA1l0EHuU1kANhg8tG+ij1fZ4Tv2hSaXIrfY6szvqKREB96Pf2+GTlApNNVQG9XLzCDhD5siTnuuxKvclS6+1l0kVp1mY8XrYGMTlqhjkmj7oxOxXzXxxAAm7OyypocJqv70DJRgl2FM6Yxou1QlNTYT/z9g0M1IMvOpA50xnkZ3ioR/ZvTYU3x5CtAl9D5rId8QddbeJPCizNSpdxYOcu39NndXYM2NhfAGJ+wI0S006C1LOuz+o=
    on_success: change
    on_failure: always
deploy:
- provider: releases
  api_key:
    secure: iwVenKOpRlggj0DEU+reIcLTCENPT9EUCh+PCOF0tO0iAjp6mcMz7C9PvWmLJI5X1PMsjJ/0FP/8kRfBw1xNMksXskQ4O7Lr25W/3gk8OUo0ONaU1jbOEKm4HS0sj6476o9IVIxr+0ZN6bY9l/31Gt+vzddygWBhYe4XoQ5u25r5xwXnEiGG3vwgTO7/tLHxwtDL6mwFjhZC6MSrZtPxx3Wxm1WujpESvZBYOmPUzUUBPCW0xA62CBoAzFjY3MZGz898+vKCtBlkUmH0BJW3dWoHpxwXny7impjzg0Kw5kxRU3isxAy/w24y3NvVB7wnrkBIQFcTYRFZ8h3HEz54Sxq6jkoexwRdZtDLe4XrrEUYucwe81Pc+5wO8887sEUNbYwDPm4mProSGbBb8WmxkgozuCC9drxiW01M5YpqzaHSoXpMFSJtRTxE5NqRxf83NOaGmU7ZXs6WW/YZVbkV3eBRBtSdnLrFAy5xb9fL/UkD9aU+sVdEnHL+tEbcTPQIBn0DCKoi5MRvXICy/kX0JaVKKCcTrXATFN88U8lYSMOv9zt3uhKQtGjMRl/FS23kftl7aopyajiGU/ab7lBW5iSUi7oBxctzSohE1ng0DO4vfBB+5JOaN9FkbssrDU4YiY4YnivLQCBErIy9es+q7nINL3ABMekq4YU3vks6mpc=
  file_glob: true
  file: dist/phovea_clustering*.egg
  on:
    tags: true
    repo: phovea/phovea_clustering
- provider: pypi
  user: caleydo-bot
  password:
    secure: CqSNo9hw9BgbXNFfnxFgjiMy941zYQ/5u4+TBasGDTW400964NlNB32/HUIm0eQOxrnO9W734+3PSLsT0LFFarLnLSm1D6/ufsxZ0YyTJ3NFEzSFH6KhsN99DyyFxmcfV4srTz1CILtL3O//2edjUPNJArEQxelqTOlFjji3L4N4JUAaefoozgdCwhWbXAi+ADSuLnezvPx2SGVUbvlHF7dWA7ESZrLsfxxY90vnBCsZ/CKoumxyg4BjbgCc8hhFPJqmmVodSqmS45kkklHt8UTG8BzgwVFj3CA+V7us2Z4Uiw0ruMXGDSXG8s4I6M/V3SmazKrQcAjYwH13gJDFKLku5qTfY8te2qy7GPIv7weh3w9b7qaBHlr7rG+Y4PPtcJV3rgOU2FvRN2j9btJGKFqq8L3r8ku4qQOFb2svXN0tdfVBRz4dpurYIBgXwPJXe0C61pjnIf/Cu7t8so76rRf1sZIOIm2JXrjHsEYk6z/5jwqYt7W90Sl6shlEw0/L+coi1C/SglSKdgtc9dcGIU6hLPSR2I++uTPhhtP9EgBISbLScN2suP+upnFHkaYcAU/EGGKh0p+EymUO9OUYHQbfXGG25dtEZFPW2CPJdcLq4N+edwtBgIf8DIed6vmmt+guT9CwQ+E4TVA+BOPLvrFY9sq9zuv5l4cj0ARcAjU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: phovea/phovea_clustering
